#!/usr/bin/env bash
workspaces() {
  icons=("", "", "", "", "", "", "", "", "", "")

  # Get Hyprland workspaces 
  readarray -t wkspaces < <(hyprctl workspaces | grep "workspace ID" | cut -d ' ' -f3)
  IFS=$'\n' wkspaces=($(sort -n <<<"${wkspaces[*]}"))
  unset IFS

  # Get active workspace
  wsactive=$(hyprctl activeworkspace | grep "workspace ID" | cut -d ' ' -f3)

  # Generate workspace widged
  output="(box :orientation \"h\" :class \"works\" :spacing \"-1\" :halign \"center\" :space-evenly \"false\""

  for ws in "${wkspaces[@]}"; do
    class="w0"
    if [[ "$ws" == "$wsactive" ]]; then
      class="w0$ws"
    fi
    bt="(button :onclick \"hyprctl dispatch workspace $ws\" :class \"$class\" \"${ws}: ${icons[$ws]}\")"
    output=$(printf '%b %b' "$output" "$bt")
  done

  output=$(printf '%b )' "$output")

  echo -e "$output"
}

handle() {
  case $1 in
    workspace*) workspaces ;;
    focusedmon*) workspaces ;;
  esac
}

# Get workspaces an generate widget on startup
workspaces

# Listen for active workspace change
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
